// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/dDan4a/tsukuyomi.Storage -o storage_mock.go -n StorageMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	mm_tsukuyomi "github.com/dDan4a/tsukuyomi"
	"github.com/gojuno/minimock/v3"
)

// StorageMock implements mm_tsukuyomi.Storage
type StorageMock[ID, K, T comparable] struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteState          func(ctx context.Context, id ID) (err error)
	funcDeleteStateOrigin    string
	inspectFuncDeleteState   func(ctx context.Context, id ID)
	afterDeleteStateCounter  uint64
	beforeDeleteStateCounter uint64
	DeleteStateMock          mStorageMockDeleteState[ID, K, T]

	funcGetState          func(ctx context.Context, id ID) (p1 mm_tsukuyomi.State[K, T], err error)
	funcGetStateOrigin    string
	inspectFuncGetState   func(ctx context.Context, id ID)
	afterGetStateCounter  uint64
	beforeGetStateCounter uint64
	GetStateMock          mStorageMockGetState[ID, K, T]

	funcSaveState          func(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T]) (err error)
	funcSaveStateOrigin    string
	inspectFuncSaveState   func(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T])
	afterSaveStateCounter  uint64
	beforeSaveStateCounter uint64
	SaveStateMock          mStorageMockSaveState[ID, K, T]
}

// NewStorageMock returns a mock for mm_tsukuyomi.Storage
func NewStorageMock[ID, K, T comparable](t minimock.Tester) *StorageMock[ID, K, T] {
	m := &StorageMock[ID, K, T]{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteStateMock = mStorageMockDeleteState[ID, K, T]{mock: m}
	m.DeleteStateMock.callArgs = []*StorageMockDeleteStateParams[ID, K, T]{}

	m.GetStateMock = mStorageMockGetState[ID, K, T]{mock: m}
	m.GetStateMock.callArgs = []*StorageMockGetStateParams[ID, K, T]{}

	m.SaveStateMock = mStorageMockSaveState[ID, K, T]{mock: m}
	m.SaveStateMock.callArgs = []*StorageMockSaveStateParams[ID, K, T]{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mStorageMockDeleteState[ID, K, T comparable] struct {
	optional           bool
	mock               *StorageMock[ID, K, T]
	defaultExpectation *StorageMockDeleteStateExpectation[ID, K, T]
	expectations       []*StorageMockDeleteStateExpectation[ID, K, T]

	callArgs []*StorageMockDeleteStateParams[ID, K, T]
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockDeleteStateExpectation specifies expectation struct of the Storage.DeleteState
type StorageMockDeleteStateExpectation[ID, K, T comparable] struct {
	mock               *StorageMock[ID, K, T]
	params             *StorageMockDeleteStateParams[ID, K, T]
	paramPtrs          *StorageMockDeleteStateParamPtrs[ID, K, T]
	expectationOrigins StorageMockDeleteStateExpectationOrigins
	results            *StorageMockDeleteStateResults[ID, K, T]
	returnOrigin       string
	Counter            uint64
}

// StorageMockDeleteStateParams contains parameters of the Storage.DeleteState
type StorageMockDeleteStateParams[ID, K, T comparable] struct {
	ctx context.Context
	id  ID
}

// StorageMockDeleteStateParamPtrs contains pointers to parameters of the Storage.DeleteState
type StorageMockDeleteStateParamPtrs[ID, K, T comparable] struct {
	ctx *context.Context
	id  *ID
}

// StorageMockDeleteStateResults contains results of the Storage.DeleteState
type StorageMockDeleteStateResults[ID, K, T comparable] struct {
	err error
}

// StorageMockDeleteStateOrigins contains origins of expectations of the Storage.DeleteState
type StorageMockDeleteStateExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Optional() *mStorageMockDeleteState[ID, K, T] {
	mmDeleteState.optional = true
	return mmDeleteState
}

// Expect sets up expected params for Storage.DeleteState
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Expect(ctx context.Context, id ID) *mStorageMockDeleteState[ID, K, T] {
	if mmDeleteState.mock.funcDeleteState != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Set")
	}

	if mmDeleteState.defaultExpectation == nil {
		mmDeleteState.defaultExpectation = &StorageMockDeleteStateExpectation[ID, K, T]{}
	}

	if mmDeleteState.defaultExpectation.paramPtrs != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by ExpectParams functions")
	}

	mmDeleteState.defaultExpectation.params = &StorageMockDeleteStateParams[ID, K, T]{ctx, id}
	mmDeleteState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteState.expectations {
		if minimock.Equal(e.params, mmDeleteState.defaultExpectation.params) {
			mmDeleteState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteState.defaultExpectation.params)
		}
	}

	return mmDeleteState
}

// ExpectCtxParam1 sets up expected param ctx for Storage.DeleteState
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) ExpectCtxParam1(ctx context.Context) *mStorageMockDeleteState[ID, K, T] {
	if mmDeleteState.mock.funcDeleteState != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Set")
	}

	if mmDeleteState.defaultExpectation == nil {
		mmDeleteState.defaultExpectation = &StorageMockDeleteStateExpectation[ID, K, T]{}
	}

	if mmDeleteState.defaultExpectation.params != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Expect")
	}

	if mmDeleteState.defaultExpectation.paramPtrs == nil {
		mmDeleteState.defaultExpectation.paramPtrs = &StorageMockDeleteStateParamPtrs[ID, K, T]{}
	}
	mmDeleteState.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteState
}

// ExpectIdParam2 sets up expected param id for Storage.DeleteState
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) ExpectIdParam2(id ID) *mStorageMockDeleteState[ID, K, T] {
	if mmDeleteState.mock.funcDeleteState != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Set")
	}

	if mmDeleteState.defaultExpectation == nil {
		mmDeleteState.defaultExpectation = &StorageMockDeleteStateExpectation[ID, K, T]{}
	}

	if mmDeleteState.defaultExpectation.params != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Expect")
	}

	if mmDeleteState.defaultExpectation.paramPtrs == nil {
		mmDeleteState.defaultExpectation.paramPtrs = &StorageMockDeleteStateParamPtrs[ID, K, T]{}
	}
	mmDeleteState.defaultExpectation.paramPtrs.id = &id
	mmDeleteState.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmDeleteState
}

// Inspect accepts an inspector function that has same arguments as the Storage.DeleteState
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Inspect(f func(ctx context.Context, id ID)) *mStorageMockDeleteState[ID, K, T] {
	if mmDeleteState.mock.inspectFuncDeleteState != nil {
		mmDeleteState.mock.t.Fatalf("Inspect function is already set for StorageMock.DeleteState")
	}

	mmDeleteState.mock.inspectFuncDeleteState = f

	return mmDeleteState
}

// Return sets up results that will be returned by Storage.DeleteState
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Return(err error) *StorageMock[ID, K, T] {
	if mmDeleteState.mock.funcDeleteState != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Set")
	}

	if mmDeleteState.defaultExpectation == nil {
		mmDeleteState.defaultExpectation = &StorageMockDeleteStateExpectation[ID, K, T]{mock: mmDeleteState.mock}
	}
	mmDeleteState.defaultExpectation.results = &StorageMockDeleteStateResults[ID, K, T]{err}
	mmDeleteState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteState.mock
}

// Set uses given function f to mock the Storage.DeleteState method
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Set(f func(ctx context.Context, id ID) (err error)) *StorageMock[ID, K, T] {
	if mmDeleteState.defaultExpectation != nil {
		mmDeleteState.mock.t.Fatalf("Default expectation is already set for the Storage.DeleteState method")
	}

	if len(mmDeleteState.expectations) > 0 {
		mmDeleteState.mock.t.Fatalf("Some expectations are already set for the Storage.DeleteState method")
	}

	mmDeleteState.mock.funcDeleteState = f
	mmDeleteState.mock.funcDeleteStateOrigin = minimock.CallerInfo(1)
	return mmDeleteState.mock
}

// When sets expectation for the Storage.DeleteState which will trigger the result defined by the following
// Then helper
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) When(ctx context.Context, id ID) *StorageMockDeleteStateExpectation[ID, K, T] {
	if mmDeleteState.mock.funcDeleteState != nil {
		mmDeleteState.mock.t.Fatalf("StorageMock.DeleteState mock is already set by Set")
	}

	expectation := &StorageMockDeleteStateExpectation[ID, K, T]{
		mock:               mmDeleteState.mock,
		params:             &StorageMockDeleteStateParams[ID, K, T]{ctx, id},
		expectationOrigins: StorageMockDeleteStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteState.expectations = append(mmDeleteState.expectations, expectation)
	return expectation
}

// Then sets up Storage.DeleteState return parameters for the expectation previously defined by the When method
func (e *StorageMockDeleteStateExpectation[ID, K, T]) Then(err error) *StorageMock[ID, K, T] {
	e.results = &StorageMockDeleteStateResults[ID, K, T]{err}
	return e.mock
}

// Times sets number of times Storage.DeleteState should be invoked
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Times(n uint64) *mStorageMockDeleteState[ID, K, T] {
	if n == 0 {
		mmDeleteState.mock.t.Fatalf("Times of StorageMock.DeleteState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteState.expectedInvocations, n)
	mmDeleteState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteState
}

func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) invocationsDone() bool {
	if len(mmDeleteState.expectations) == 0 && mmDeleteState.defaultExpectation == nil && mmDeleteState.mock.funcDeleteState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteState.mock.afterDeleteStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteState implements mm_tsukuyomi.Storage
func (mmDeleteState *StorageMock[ID, K, T]) DeleteState(ctx context.Context, id ID) (err error) {
	mm_atomic.AddUint64(&mmDeleteState.beforeDeleteStateCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteState.afterDeleteStateCounter, 1)

	mmDeleteState.t.Helper()

	if mmDeleteState.inspectFuncDeleteState != nil {
		mmDeleteState.inspectFuncDeleteState(ctx, id)
	}

	mm_params := StorageMockDeleteStateParams[ID, K, T]{ctx, id}

	// Record call args
	mmDeleteState.DeleteStateMock.mutex.Lock()
	mmDeleteState.DeleteStateMock.callArgs = append(mmDeleteState.DeleteStateMock.callArgs, &mm_params)
	mmDeleteState.DeleteStateMock.mutex.Unlock()

	for _, e := range mmDeleteState.DeleteStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteState.DeleteStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteState.DeleteStateMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteState.DeleteStateMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteState.DeleteStateMock.defaultExpectation.paramPtrs

		mm_got := StorageMockDeleteStateParams[ID, K, T]{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteState.t.Errorf("StorageMock.DeleteState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteState.DeleteStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmDeleteState.t.Errorf("StorageMock.DeleteState got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteState.DeleteStateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteState.t.Errorf("StorageMock.DeleteState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteState.DeleteStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteState.DeleteStateMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteState.t.Fatal("No results are set for the StorageMock.DeleteState")
		}
		return (*mm_results).err
	}
	if mmDeleteState.funcDeleteState != nil {
		return mmDeleteState.funcDeleteState(ctx, id)
	}
	mmDeleteState.t.Fatalf("Unexpected call to StorageMock.DeleteState. %v %v", ctx, id)
	return
}

// DeleteStateAfterCounter returns a count of finished StorageMock.DeleteState invocations
func (mmDeleteState *StorageMock[ID, K, T]) DeleteStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteState.afterDeleteStateCounter)
}

// DeleteStateBeforeCounter returns a count of StorageMock.DeleteState invocations
func (mmDeleteState *StorageMock[ID, K, T]) DeleteStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteState.beforeDeleteStateCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.DeleteState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteState *mStorageMockDeleteState[ID, K, T]) Calls() []*StorageMockDeleteStateParams[ID, K, T] {
	mmDeleteState.mutex.RLock()

	argCopy := make([]*StorageMockDeleteStateParams[ID, K, T], len(mmDeleteState.callArgs))
	copy(argCopy, mmDeleteState.callArgs)

	mmDeleteState.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteStateDone returns true if the count of the DeleteState invocations corresponds
// the number of defined expectations
func (m *StorageMock[ID, K, T]) MinimockDeleteStateDone() bool {
	if m.DeleteStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteStateMock.invocationsDone()
}

// MinimockDeleteStateInspect logs each unmet expectation
func (m *StorageMock[ID, K, T]) MinimockDeleteStateInspect() {
	for _, e := range m.DeleteStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.DeleteState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteStateCounter := mm_atomic.LoadUint64(&m.afterDeleteStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteStateMock.defaultExpectation != nil && afterDeleteStateCounter < 1 {
		if m.DeleteStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.DeleteState at\n%s", m.DeleteStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.DeleteState at\n%s with params: %#v", m.DeleteStateMock.defaultExpectation.expectationOrigins.origin, *m.DeleteStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteState != nil && afterDeleteStateCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.DeleteState at\n%s", m.funcDeleteStateOrigin)
	}

	if !m.DeleteStateMock.invocationsDone() && afterDeleteStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.DeleteState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteStateMock.expectedInvocations), m.DeleteStateMock.expectedInvocationsOrigin, afterDeleteStateCounter)
	}
}

type mStorageMockGetState[ID, K, T comparable] struct {
	optional           bool
	mock               *StorageMock[ID, K, T]
	defaultExpectation *StorageMockGetStateExpectation[ID, K, T]
	expectations       []*StorageMockGetStateExpectation[ID, K, T]

	callArgs []*StorageMockGetStateParams[ID, K, T]
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockGetStateExpectation specifies expectation struct of the Storage.GetState
type StorageMockGetStateExpectation[ID, K, T comparable] struct {
	mock               *StorageMock[ID, K, T]
	params             *StorageMockGetStateParams[ID, K, T]
	paramPtrs          *StorageMockGetStateParamPtrs[ID, K, T]
	expectationOrigins StorageMockGetStateExpectationOrigins
	results            *StorageMockGetStateResults[ID, K, T]
	returnOrigin       string
	Counter            uint64
}

// StorageMockGetStateParams contains parameters of the Storage.GetState
type StorageMockGetStateParams[ID, K, T comparable] struct {
	ctx context.Context
	id  ID
}

// StorageMockGetStateParamPtrs contains pointers to parameters of the Storage.GetState
type StorageMockGetStateParamPtrs[ID, K, T comparable] struct {
	ctx *context.Context
	id  *ID
}

// StorageMockGetStateResults contains results of the Storage.GetState
type StorageMockGetStateResults[ID, K, T comparable] struct {
	p1  mm_tsukuyomi.State[K, T]
	err error
}

// StorageMockGetStateOrigins contains origins of expectations of the Storage.GetState
type StorageMockGetStateExpectationOrigins struct {
	origin    string
	originCtx string
	originId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetState *mStorageMockGetState[ID, K, T]) Optional() *mStorageMockGetState[ID, K, T] {
	mmGetState.optional = true
	return mmGetState
}

// Expect sets up expected params for Storage.GetState
func (mmGetState *mStorageMockGetState[ID, K, T]) Expect(ctx context.Context, id ID) *mStorageMockGetState[ID, K, T] {
	if mmGetState.mock.funcGetState != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Set")
	}

	if mmGetState.defaultExpectation == nil {
		mmGetState.defaultExpectation = &StorageMockGetStateExpectation[ID, K, T]{}
	}

	if mmGetState.defaultExpectation.paramPtrs != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by ExpectParams functions")
	}

	mmGetState.defaultExpectation.params = &StorageMockGetStateParams[ID, K, T]{ctx, id}
	mmGetState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetState.expectations {
		if minimock.Equal(e.params, mmGetState.defaultExpectation.params) {
			mmGetState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetState.defaultExpectation.params)
		}
	}

	return mmGetState
}

// ExpectCtxParam1 sets up expected param ctx for Storage.GetState
func (mmGetState *mStorageMockGetState[ID, K, T]) ExpectCtxParam1(ctx context.Context) *mStorageMockGetState[ID, K, T] {
	if mmGetState.mock.funcGetState != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Set")
	}

	if mmGetState.defaultExpectation == nil {
		mmGetState.defaultExpectation = &StorageMockGetStateExpectation[ID, K, T]{}
	}

	if mmGetState.defaultExpectation.params != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Expect")
	}

	if mmGetState.defaultExpectation.paramPtrs == nil {
		mmGetState.defaultExpectation.paramPtrs = &StorageMockGetStateParamPtrs[ID, K, T]{}
	}
	mmGetState.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetState
}

// ExpectIdParam2 sets up expected param id for Storage.GetState
func (mmGetState *mStorageMockGetState[ID, K, T]) ExpectIdParam2(id ID) *mStorageMockGetState[ID, K, T] {
	if mmGetState.mock.funcGetState != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Set")
	}

	if mmGetState.defaultExpectation == nil {
		mmGetState.defaultExpectation = &StorageMockGetStateExpectation[ID, K, T]{}
	}

	if mmGetState.defaultExpectation.params != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Expect")
	}

	if mmGetState.defaultExpectation.paramPtrs == nil {
		mmGetState.defaultExpectation.paramPtrs = &StorageMockGetStateParamPtrs[ID, K, T]{}
	}
	mmGetState.defaultExpectation.paramPtrs.id = &id
	mmGetState.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetState
}

// Inspect accepts an inspector function that has same arguments as the Storage.GetState
func (mmGetState *mStorageMockGetState[ID, K, T]) Inspect(f func(ctx context.Context, id ID)) *mStorageMockGetState[ID, K, T] {
	if mmGetState.mock.inspectFuncGetState != nil {
		mmGetState.mock.t.Fatalf("Inspect function is already set for StorageMock.GetState")
	}

	mmGetState.mock.inspectFuncGetState = f

	return mmGetState
}

// Return sets up results that will be returned by Storage.GetState
func (mmGetState *mStorageMockGetState[ID, K, T]) Return(p1 mm_tsukuyomi.State[K, T], err error) *StorageMock[ID, K, T] {
	if mmGetState.mock.funcGetState != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Set")
	}

	if mmGetState.defaultExpectation == nil {
		mmGetState.defaultExpectation = &StorageMockGetStateExpectation[ID, K, T]{mock: mmGetState.mock}
	}
	mmGetState.defaultExpectation.results = &StorageMockGetStateResults[ID, K, T]{p1, err}
	mmGetState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetState.mock
}

// Set uses given function f to mock the Storage.GetState method
func (mmGetState *mStorageMockGetState[ID, K, T]) Set(f func(ctx context.Context, id ID) (p1 mm_tsukuyomi.State[K, T], err error)) *StorageMock[ID, K, T] {
	if mmGetState.defaultExpectation != nil {
		mmGetState.mock.t.Fatalf("Default expectation is already set for the Storage.GetState method")
	}

	if len(mmGetState.expectations) > 0 {
		mmGetState.mock.t.Fatalf("Some expectations are already set for the Storage.GetState method")
	}

	mmGetState.mock.funcGetState = f
	mmGetState.mock.funcGetStateOrigin = minimock.CallerInfo(1)
	return mmGetState.mock
}

// When sets expectation for the Storage.GetState which will trigger the result defined by the following
// Then helper
func (mmGetState *mStorageMockGetState[ID, K, T]) When(ctx context.Context, id ID) *StorageMockGetStateExpectation[ID, K, T] {
	if mmGetState.mock.funcGetState != nil {
		mmGetState.mock.t.Fatalf("StorageMock.GetState mock is already set by Set")
	}

	expectation := &StorageMockGetStateExpectation[ID, K, T]{
		mock:               mmGetState.mock,
		params:             &StorageMockGetStateParams[ID, K, T]{ctx, id},
		expectationOrigins: StorageMockGetStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetState.expectations = append(mmGetState.expectations, expectation)
	return expectation
}

// Then sets up Storage.GetState return parameters for the expectation previously defined by the When method
func (e *StorageMockGetStateExpectation[ID, K, T]) Then(p1 mm_tsukuyomi.State[K, T], err error) *StorageMock[ID, K, T] {
	e.results = &StorageMockGetStateResults[ID, K, T]{p1, err}
	return e.mock
}

// Times sets number of times Storage.GetState should be invoked
func (mmGetState *mStorageMockGetState[ID, K, T]) Times(n uint64) *mStorageMockGetState[ID, K, T] {
	if n == 0 {
		mmGetState.mock.t.Fatalf("Times of StorageMock.GetState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetState.expectedInvocations, n)
	mmGetState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetState
}

func (mmGetState *mStorageMockGetState[ID, K, T]) invocationsDone() bool {
	if len(mmGetState.expectations) == 0 && mmGetState.defaultExpectation == nil && mmGetState.mock.funcGetState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetState.mock.afterGetStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetState implements mm_tsukuyomi.Storage
func (mmGetState *StorageMock[ID, K, T]) GetState(ctx context.Context, id ID) (p1 mm_tsukuyomi.State[K, T], err error) {
	mm_atomic.AddUint64(&mmGetState.beforeGetStateCounter, 1)
	defer mm_atomic.AddUint64(&mmGetState.afterGetStateCounter, 1)

	mmGetState.t.Helper()

	if mmGetState.inspectFuncGetState != nil {
		mmGetState.inspectFuncGetState(ctx, id)
	}

	mm_params := StorageMockGetStateParams[ID, K, T]{ctx, id}

	// Record call args
	mmGetState.GetStateMock.mutex.Lock()
	mmGetState.GetStateMock.callArgs = append(mmGetState.GetStateMock.callArgs, &mm_params)
	mmGetState.GetStateMock.mutex.Unlock()

	for _, e := range mmGetState.GetStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmGetState.GetStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetState.GetStateMock.defaultExpectation.Counter, 1)
		mm_want := mmGetState.GetStateMock.defaultExpectation.params
		mm_want_ptrs := mmGetState.GetStateMock.defaultExpectation.paramPtrs

		mm_got := StorageMockGetStateParams[ID, K, T]{ctx, id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetState.t.Errorf("StorageMock.GetState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetState.GetStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetState.t.Errorf("StorageMock.GetState got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetState.GetStateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetState.t.Errorf("StorageMock.GetState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetState.GetStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetState.GetStateMock.defaultExpectation.results
		if mm_results == nil {
			mmGetState.t.Fatal("No results are set for the StorageMock.GetState")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmGetState.funcGetState != nil {
		return mmGetState.funcGetState(ctx, id)
	}
	mmGetState.t.Fatalf("Unexpected call to StorageMock.GetState. %v %v", ctx, id)
	return
}

// GetStateAfterCounter returns a count of finished StorageMock.GetState invocations
func (mmGetState *StorageMock[ID, K, T]) GetStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetState.afterGetStateCounter)
}

// GetStateBeforeCounter returns a count of StorageMock.GetState invocations
func (mmGetState *StorageMock[ID, K, T]) GetStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetState.beforeGetStateCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.GetState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetState *mStorageMockGetState[ID, K, T]) Calls() []*StorageMockGetStateParams[ID, K, T] {
	mmGetState.mutex.RLock()

	argCopy := make([]*StorageMockGetStateParams[ID, K, T], len(mmGetState.callArgs))
	copy(argCopy, mmGetState.callArgs)

	mmGetState.mutex.RUnlock()

	return argCopy
}

// MinimockGetStateDone returns true if the count of the GetState invocations corresponds
// the number of defined expectations
func (m *StorageMock[ID, K, T]) MinimockGetStateDone() bool {
	if m.GetStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetStateMock.invocationsDone()
}

// MinimockGetStateInspect logs each unmet expectation
func (m *StorageMock[ID, K, T]) MinimockGetStateInspect() {
	for _, e := range m.GetStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.GetState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetStateCounter := mm_atomic.LoadUint64(&m.afterGetStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetStateMock.defaultExpectation != nil && afterGetStateCounter < 1 {
		if m.GetStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.GetState at\n%s", m.GetStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.GetState at\n%s with params: %#v", m.GetStateMock.defaultExpectation.expectationOrigins.origin, *m.GetStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetState != nil && afterGetStateCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.GetState at\n%s", m.funcGetStateOrigin)
	}

	if !m.GetStateMock.invocationsDone() && afterGetStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.GetState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetStateMock.expectedInvocations), m.GetStateMock.expectedInvocationsOrigin, afterGetStateCounter)
	}
}

type mStorageMockSaveState[ID, K, T comparable] struct {
	optional           bool
	mock               *StorageMock[ID, K, T]
	defaultExpectation *StorageMockSaveStateExpectation[ID, K, T]
	expectations       []*StorageMockSaveStateExpectation[ID, K, T]

	callArgs []*StorageMockSaveStateParams[ID, K, T]
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// StorageMockSaveStateExpectation specifies expectation struct of the Storage.SaveState
type StorageMockSaveStateExpectation[ID, K, T comparable] struct {
	mock               *StorageMock[ID, K, T]
	params             *StorageMockSaveStateParams[ID, K, T]
	paramPtrs          *StorageMockSaveStateParamPtrs[ID, K, T]
	expectationOrigins StorageMockSaveStateExpectationOrigins
	results            *StorageMockSaveStateResults[ID, K, T]
	returnOrigin       string
	Counter            uint64
}

// StorageMockSaveStateParams contains parameters of the Storage.SaveState
type StorageMockSaveStateParams[ID, K, T comparable] struct {
	ctx   context.Context
	id    ID
	state mm_tsukuyomi.State[K, T]
}

// StorageMockSaveStateParamPtrs contains pointers to parameters of the Storage.SaveState
type StorageMockSaveStateParamPtrs[ID, K, T comparable] struct {
	ctx   *context.Context
	id    *ID
	state *mm_tsukuyomi.State[K, T]
}

// StorageMockSaveStateResults contains results of the Storage.SaveState
type StorageMockSaveStateResults[ID, K, T comparable] struct {
	err error
}

// StorageMockSaveStateOrigins contains origins of expectations of the Storage.SaveState
type StorageMockSaveStateExpectationOrigins struct {
	origin      string
	originCtx   string
	originId    string
	originState string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Optional() *mStorageMockSaveState[ID, K, T] {
	mmSaveState.optional = true
	return mmSaveState
}

// Expect sets up expected params for Storage.SaveState
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Expect(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T]) *mStorageMockSaveState[ID, K, T] {
	if mmSaveState.mock.funcSaveState != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Set")
	}

	if mmSaveState.defaultExpectation == nil {
		mmSaveState.defaultExpectation = &StorageMockSaveStateExpectation[ID, K, T]{}
	}

	if mmSaveState.defaultExpectation.paramPtrs != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by ExpectParams functions")
	}

	mmSaveState.defaultExpectation.params = &StorageMockSaveStateParams[ID, K, T]{ctx, id, state}
	mmSaveState.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSaveState.expectations {
		if minimock.Equal(e.params, mmSaveState.defaultExpectation.params) {
			mmSaveState.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSaveState.defaultExpectation.params)
		}
	}

	return mmSaveState
}

// ExpectCtxParam1 sets up expected param ctx for Storage.SaveState
func (mmSaveState *mStorageMockSaveState[ID, K, T]) ExpectCtxParam1(ctx context.Context) *mStorageMockSaveState[ID, K, T] {
	if mmSaveState.mock.funcSaveState != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Set")
	}

	if mmSaveState.defaultExpectation == nil {
		mmSaveState.defaultExpectation = &StorageMockSaveStateExpectation[ID, K, T]{}
	}

	if mmSaveState.defaultExpectation.params != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Expect")
	}

	if mmSaveState.defaultExpectation.paramPtrs == nil {
		mmSaveState.defaultExpectation.paramPtrs = &StorageMockSaveStateParamPtrs[ID, K, T]{}
	}
	mmSaveState.defaultExpectation.paramPtrs.ctx = &ctx
	mmSaveState.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSaveState
}

// ExpectIdParam2 sets up expected param id for Storage.SaveState
func (mmSaveState *mStorageMockSaveState[ID, K, T]) ExpectIdParam2(id ID) *mStorageMockSaveState[ID, K, T] {
	if mmSaveState.mock.funcSaveState != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Set")
	}

	if mmSaveState.defaultExpectation == nil {
		mmSaveState.defaultExpectation = &StorageMockSaveStateExpectation[ID, K, T]{}
	}

	if mmSaveState.defaultExpectation.params != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Expect")
	}

	if mmSaveState.defaultExpectation.paramPtrs == nil {
		mmSaveState.defaultExpectation.paramPtrs = &StorageMockSaveStateParamPtrs[ID, K, T]{}
	}
	mmSaveState.defaultExpectation.paramPtrs.id = &id
	mmSaveState.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmSaveState
}

// ExpectStateParam3 sets up expected param state for Storage.SaveState
func (mmSaveState *mStorageMockSaveState[ID, K, T]) ExpectStateParam3(state mm_tsukuyomi.State[K, T]) *mStorageMockSaveState[ID, K, T] {
	if mmSaveState.mock.funcSaveState != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Set")
	}

	if mmSaveState.defaultExpectation == nil {
		mmSaveState.defaultExpectation = &StorageMockSaveStateExpectation[ID, K, T]{}
	}

	if mmSaveState.defaultExpectation.params != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Expect")
	}

	if mmSaveState.defaultExpectation.paramPtrs == nil {
		mmSaveState.defaultExpectation.paramPtrs = &StorageMockSaveStateParamPtrs[ID, K, T]{}
	}
	mmSaveState.defaultExpectation.paramPtrs.state = &state
	mmSaveState.defaultExpectation.expectationOrigins.originState = minimock.CallerInfo(1)

	return mmSaveState
}

// Inspect accepts an inspector function that has same arguments as the Storage.SaveState
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Inspect(f func(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T])) *mStorageMockSaveState[ID, K, T] {
	if mmSaveState.mock.inspectFuncSaveState != nil {
		mmSaveState.mock.t.Fatalf("Inspect function is already set for StorageMock.SaveState")
	}

	mmSaveState.mock.inspectFuncSaveState = f

	return mmSaveState
}

// Return sets up results that will be returned by Storage.SaveState
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Return(err error) *StorageMock[ID, K, T] {
	if mmSaveState.mock.funcSaveState != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Set")
	}

	if mmSaveState.defaultExpectation == nil {
		mmSaveState.defaultExpectation = &StorageMockSaveStateExpectation[ID, K, T]{mock: mmSaveState.mock}
	}
	mmSaveState.defaultExpectation.results = &StorageMockSaveStateResults[ID, K, T]{err}
	mmSaveState.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSaveState.mock
}

// Set uses given function f to mock the Storage.SaveState method
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Set(f func(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T]) (err error)) *StorageMock[ID, K, T] {
	if mmSaveState.defaultExpectation != nil {
		mmSaveState.mock.t.Fatalf("Default expectation is already set for the Storage.SaveState method")
	}

	if len(mmSaveState.expectations) > 0 {
		mmSaveState.mock.t.Fatalf("Some expectations are already set for the Storage.SaveState method")
	}

	mmSaveState.mock.funcSaveState = f
	mmSaveState.mock.funcSaveStateOrigin = minimock.CallerInfo(1)
	return mmSaveState.mock
}

// When sets expectation for the Storage.SaveState which will trigger the result defined by the following
// Then helper
func (mmSaveState *mStorageMockSaveState[ID, K, T]) When(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T]) *StorageMockSaveStateExpectation[ID, K, T] {
	if mmSaveState.mock.funcSaveState != nil {
		mmSaveState.mock.t.Fatalf("StorageMock.SaveState mock is already set by Set")
	}

	expectation := &StorageMockSaveStateExpectation[ID, K, T]{
		mock:               mmSaveState.mock,
		params:             &StorageMockSaveStateParams[ID, K, T]{ctx, id, state},
		expectationOrigins: StorageMockSaveStateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSaveState.expectations = append(mmSaveState.expectations, expectation)
	return expectation
}

// Then sets up Storage.SaveState return parameters for the expectation previously defined by the When method
func (e *StorageMockSaveStateExpectation[ID, K, T]) Then(err error) *StorageMock[ID, K, T] {
	e.results = &StorageMockSaveStateResults[ID, K, T]{err}
	return e.mock
}

// Times sets number of times Storage.SaveState should be invoked
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Times(n uint64) *mStorageMockSaveState[ID, K, T] {
	if n == 0 {
		mmSaveState.mock.t.Fatalf("Times of StorageMock.SaveState mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSaveState.expectedInvocations, n)
	mmSaveState.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSaveState
}

func (mmSaveState *mStorageMockSaveState[ID, K, T]) invocationsDone() bool {
	if len(mmSaveState.expectations) == 0 && mmSaveState.defaultExpectation == nil && mmSaveState.mock.funcSaveState == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSaveState.mock.afterSaveStateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSaveState.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SaveState implements mm_tsukuyomi.Storage
func (mmSaveState *StorageMock[ID, K, T]) SaveState(ctx context.Context, id ID, state mm_tsukuyomi.State[K, T]) (err error) {
	mm_atomic.AddUint64(&mmSaveState.beforeSaveStateCounter, 1)
	defer mm_atomic.AddUint64(&mmSaveState.afterSaveStateCounter, 1)

	mmSaveState.t.Helper()

	if mmSaveState.inspectFuncSaveState != nil {
		mmSaveState.inspectFuncSaveState(ctx, id, state)
	}

	mm_params := StorageMockSaveStateParams[ID, K, T]{ctx, id, state}

	// Record call args
	mmSaveState.SaveStateMock.mutex.Lock()
	mmSaveState.SaveStateMock.callArgs = append(mmSaveState.SaveStateMock.callArgs, &mm_params)
	mmSaveState.SaveStateMock.mutex.Unlock()

	for _, e := range mmSaveState.SaveStateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSaveState.SaveStateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSaveState.SaveStateMock.defaultExpectation.Counter, 1)
		mm_want := mmSaveState.SaveStateMock.defaultExpectation.params
		mm_want_ptrs := mmSaveState.SaveStateMock.defaultExpectation.paramPtrs

		mm_got := StorageMockSaveStateParams[ID, K, T]{ctx, id, state}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSaveState.t.Errorf("StorageMock.SaveState got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveState.SaveStateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmSaveState.t.Errorf("StorageMock.SaveState got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveState.SaveStateMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

			if mm_want_ptrs.state != nil && !minimock.Equal(*mm_want_ptrs.state, mm_got.state) {
				mmSaveState.t.Errorf("StorageMock.SaveState got unexpected parameter state, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSaveState.SaveStateMock.defaultExpectation.expectationOrigins.originState, *mm_want_ptrs.state, mm_got.state, minimock.Diff(*mm_want_ptrs.state, mm_got.state))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSaveState.t.Errorf("StorageMock.SaveState got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSaveState.SaveStateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSaveState.SaveStateMock.defaultExpectation.results
		if mm_results == nil {
			mmSaveState.t.Fatal("No results are set for the StorageMock.SaveState")
		}
		return (*mm_results).err
	}
	if mmSaveState.funcSaveState != nil {
		return mmSaveState.funcSaveState(ctx, id, state)
	}
	mmSaveState.t.Fatalf("Unexpected call to StorageMock.SaveState. %v %v %v", ctx, id, state)
	return
}

// SaveStateAfterCounter returns a count of finished StorageMock.SaveState invocations
func (mmSaveState *StorageMock[ID, K, T]) SaveStateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveState.afterSaveStateCounter)
}

// SaveStateBeforeCounter returns a count of StorageMock.SaveState invocations
func (mmSaveState *StorageMock[ID, K, T]) SaveStateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSaveState.beforeSaveStateCounter)
}

// Calls returns a list of arguments used in each call to StorageMock.SaveState.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSaveState *mStorageMockSaveState[ID, K, T]) Calls() []*StorageMockSaveStateParams[ID, K, T] {
	mmSaveState.mutex.RLock()

	argCopy := make([]*StorageMockSaveStateParams[ID, K, T], len(mmSaveState.callArgs))
	copy(argCopy, mmSaveState.callArgs)

	mmSaveState.mutex.RUnlock()

	return argCopy
}

// MinimockSaveStateDone returns true if the count of the SaveState invocations corresponds
// the number of defined expectations
func (m *StorageMock[ID, K, T]) MinimockSaveStateDone() bool {
	if m.SaveStateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveStateMock.invocationsDone()
}

// MinimockSaveStateInspect logs each unmet expectation
func (m *StorageMock[ID, K, T]) MinimockSaveStateInspect() {
	for _, e := range m.SaveStateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to StorageMock.SaveState at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveStateCounter := mm_atomic.LoadUint64(&m.afterSaveStateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveStateMock.defaultExpectation != nil && afterSaveStateCounter < 1 {
		if m.SaveStateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to StorageMock.SaveState at\n%s", m.SaveStateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to StorageMock.SaveState at\n%s with params: %#v", m.SaveStateMock.defaultExpectation.expectationOrigins.origin, *m.SaveStateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSaveState != nil && afterSaveStateCounter < 1 {
		m.t.Errorf("Expected call to StorageMock.SaveState at\n%s", m.funcSaveStateOrigin)
	}

	if !m.SaveStateMock.invocationsDone() && afterSaveStateCounter > 0 {
		m.t.Errorf("Expected %d calls to StorageMock.SaveState at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveStateMock.expectedInvocations), m.SaveStateMock.expectedInvocationsOrigin, afterSaveStateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *StorageMock[ID, K, T]) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteStateInspect()

			m.MinimockGetStateInspect()

			m.MinimockSaveStateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *StorageMock[ID, K, T]) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *StorageMock[ID, K, T]) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteStateDone() &&
		m.MinimockGetStateDone() &&
		m.MinimockSaveStateDone()
}
